pages:
  stage: deploy
  script:
    - mkdir -p public
    - mkdir -p public/css
    - mkdir -p public/js
    - cp -r index.html public/
    - cp -r css/* public/css/
    - cp -r js/* public/js/
  artifacts:
    paths:
      - public
  only:
    - main
